### ISSUE TITLE
Tokyo Cabinet and imposm.parser installation

### ISSUE THREAD

**Issue by kaustavkar16** [pylayers/pylayers#239]
Hello Sir
     
While installing the tokyo cabinet and imposm.parser following errors occur

i> For tokyo cabinet installation it is showing:
fatal error C1083: Cannot open include file: 'tcbdb.h' : No such file or directory
error: command C:\\Users\\....\\Visual C++ for Python\\VC\\Bin\\amd64\\cl.exe failed with exit status 2

ii> For imposm.parser installation it is showing:
C:\\Users\\....\\Visual C++ for Python\\VC\\Include\\xlocale<342> warning C4530: C++ exception handler used but unwind semantics are not enabled. Specify /EHsc
...\imposm.parser\imposm\parser\pbf\osm.pb.h<9> fatal error C1083: Cannot open include file: 'Google/protobuf/stubs/Common.h No such file or directory
error: command C:\\Users\\....\\Visual C++ for Python\\VC\\Bin\\amd64\\cl.exe failed with exit status 2

protobuf and protoc are already installed.
Can you please suggest a fix for these errors.
![issue](https://cloud.githubusercontent.com/assets/14021885/9557176/75c7bf4a-4df7-11e5-84db-014c2a05711f.jpg)

**Comment by buguen** [comment]
Could you show me the version of setup.py you are using. The module imposm is not required for pylayers to run. It just provides an interface with the open street map format in layout.py.  

comment this line in layout.py 
# import pylayers.gis.osmparser as osm

You probably have a missing library for building tokyo cabinet

**Comment by kaustavkar16** [comment]
Thank you sir for the fix.
