### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by germanmendoza** [pylayers/pylayers#250]
Hello there.
I'm having problems installing pylayers in Windows 8.1 and Linux Ubuntu 14.04.3. I have used Anaconda2-2.4.0 in both OSs. The error is the same in both systems too. Maybe it is something easy I'm missing, but I know nothing of Python and I'm not handy with Linux systems either. The screen shot of the error is:
![image](https://cloud.githubusercontent.com/assets/13176287/11562284/528cbc7a-99cd-11e5-9202-57586335547b.png)
Thanks in advance...

**Comment by niamiot** [comment]
It seems there is an issue during the install of PIL library.
I suppose you have an anaconda distribution of python, so you should try : 
> conda install PIL
If you encountered the same issue , try an install from pip : 
> pip install PIL
Then try to reinstall pylayers.
Let me know if you manage to finish he install

**Comment by germanmendoza** [comment]
Hi Nicolas,
I followed your instructions and the installation went Ok. Thanks a lot. After that, I wanted to see if pylayers was working Ok.  I tried the 4 lines sample code:
>>> from pylayers.simul.link import *
>>> DL = DLink()
>>> DL.eval()
>>> DL._show3()

I wrote them in a .py file that I run with python. Now I get the error it is shown in the following screen shot:

![image](https://cloud.githubusercontent.com/assets/13176287/11564136/d749273c-99d7-11e5-8bda-3c6bbe2e17a8.png)

What should I do? Am I verifying if pylayers is Ok in the wrong way? Thanks again!

**Comment by niamiot** [comment]
Could you please check if you have a .pylayers (note the '.' prefix) file created in your $HOME ( a.k.a. ~)
If so , please check that under 'source' the path correspond to the directory where you cloned the pylayers project (regarding your screenshot, it should be : ~/Downloads/pylayers-master)

**Comment by germanmendoza** [comment]
Hi Nicolas.
I did what you said and now pylayers is working fine in Windows. However, in Ubuntu I got this error:
![image](https://cloud.githubusercontent.com/assets/13176287/11588542/b36b1ece-9a81-11e5-95c8-570494fa539b.png)
Thanks again!

**Comment by niamiot** [comment]
It sounds like an issue with the basemap library installation.
make an extra : 
> conda install basemap
should solve the issue

**Comment by germanmendoza** [comment]
Thanks Nicolas. Now it is working fine in Ubuntu too.
