### ISSUE TITLE
Install Pylayers

### ISSUE THREAD

**Issue by lidiaxp** [pylayers/pylayers#293]
After install PyLayers I try use multi wall model, but when write "from pylayers.antprop.coverage import *" appear an error that say "No module named Image" on selectl script, but before some scripts dont appear it. (Pillow's downloaded on computer)

**Comment by rFalque** [comment]
In "pylayers/gis/selectl.py" replace line 11
from 
`import Image`
to
`from PIL import Image`

**Comment by niamiot** [comment]
Seems @rFalque solve this.
