### ISSUE TITLE
No module named triangle

### ISSUE THREAD

**Issue by yzylining** [pylayers/pylayers#298]
from pylayers.simul.link import *
after show me this message "No module named triangle"
I installed the triangle through the "conda install triangle", but don't work, how can I solve this problem,thanks

**Comment by niamiot** [comment]
triangle is not included in conda.
You can install it using pip.
By the way, I strongly recommend to install pylayers using one of the installer available at the root of project by running [**installer_unix**](https://github.com/pylayers/pylayers/blob/master/installer_unix) or [**installer_win.bat**](https://github.com/pylayers/pylayers/blob/master/installer_win.bat) regarding your operating system (macOS/linux or windows respectively)
