### ISSUE TITLE
tolist method is not defined for vec3 class

### ISSUE THREAD

**Issue by mkoledoye** [pylayers/pylayers#300]
https://github.com/pylayers/pylayers/blob/26301dcedf0b7415de282a37df27e94d60147972/pylayers/mobility/transit/SteeringBehavior.py#L501

The `vec3` instance (returned by `localy` or `localx`) has no `tolist` method.  Was this supposed to be a numpy array that defines `tolist`?

**Comment by niamiot** [comment]
solve with  add40dd
