### ISSUE TITLE
Python 3 windows 10

### ISSUE THREAD

**Issue by lquinet1** [pylayers/pylayers#327]
Hi,

Does pylayers work with python 3? You don't notice the python version anywhere. I am not able to make it work in python 3, but in python 2.7 yes.

**Comment by buguen** [comment]
PyLayers has been written in python 2.7 and it is currently upgraded  for python 3. My current python version is 3.6.7. 
It may remain some part in the code which are still not python 3 compatible. If you noticed such situations, please post a ticket or suggest a pull request.
