### ISSUE TITLE
Creating a new layout file

### ISSUE THREAD

**Issue by reenaraj073** [pylayers/pylayers#351]
Hello everyone, I have created a new layout file for indoor environment by writing into a new .lay file , just by understanding from the already present .lay files.
My doubts:

1. Is this the right way/efficient way to define the layout file?
2. Does newly created .lay files have access to slab.ini and mat.ini files just like currently existing files? If yes?, how can i make this file access the slab and .ini files? 

Any kind of help is appreciated...
Thank you.

**Comment by horvlint** [comment]
Hello,
I found several alternatives for creating layout files:
- pylayers/gui/editor.py tool (though I found some portability issues if using with python3
- java open street map: https://josm.openstreetmap.de the layouts created with this can be imported to pylayers and saved as a .lay file

**Comment by reenaraj073** [comment]
> Hello,
> I found several alternatives for creating layout files:
> 
> * pylayers/gui/editor.py tool (though I found some portability issues if using with python3
> * java open street map: https://josm.openstreetmap.de the layouts created with this can be imported to pylayers and saved as a .lay file

Hi, thank you for your recommendations. I was not aware of the 1st option you provided. I will check this out.
