### ISSUE TITLE
install lib

### ISSUE THREAD

**Issue by shihchun** [pylayers/pylayers#354]
I've install the shapely, Basemap... with but still have some prob with python 3.8 in win10,

```
install note....
 Pip install Mayavi shapely Basemap network


Basemap Shapely   installation
pip install egos
cp3.8 python version
https://www.lfd.uci.edu/~gohlke/pythonlibs/
https://towardsdatascience.com/install-shapely-on-windows-72b6581bb46c
pyproj-3.0.0.post1-cp38-cp38-win_amd64.whl
basemap-1.2.2-cp38-cp38-win_amd64.whl
Shapely-1.7.1-cp38-cp38-win_amd64.whl
triangle-20200424-cp38-cp38-win_amd64.whl


import os
os.environ['PROJ_LIB'] = r'/Users/huangshijun/anaconda3/share/proj'

installation
cp3.8 python version

descartes
pip install descarteslabs triangle meshpy  osmapi simplejson pdbpp
pip install smopy
conda install -c conda-forge simplekml 
pip install networkx==2.0
pip install matplotlib==3.1.2
pip install scipy==1.2.1

Mayavi
conda install -c coda-forge vtk 
Pip Install  vtk_cp38.whl
conda install -c conda-forge mayavi 

********************************************************************************
WARNING: Imported VTK version (9.0) does not match the one used
         to build the TVTK classes (8.2). This may cause problems.
         Please rebuild TVTK.
********************************************************************************
下載vtk whl 版本要對上 python版本也要對上


Geo 3.6
https://trac.osgeo.org/osgeo4w/
add installed folder to path e.g. C:\OSGeo4W64\bin
```

ray trace works
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/27427042/98949237-68b1b000-2532-11eb-9f40-d58a4c3662c2.png">

DOA works
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/27427042/98949510-c9d98380-2532-11eb-88c3-92e0ec037b2e.png">

I need help, could someone provide the requirement.txt ?

```
python --version > pyversion.txt
pip freeze > requirements.txt
```

**Comment by shihchun** [comment]
exLuebber.py
debug in python 3.8

<img width="1016" alt="截圖 2020-11-13 上午1 09 51" src="https://user-images.githubusercontent.com/27427042/98972912-0c5c8980-254e-11eb-921d-9840b0ac5629.png">

add the `list()`
<img width="594" alt="截圖 2020-11-13 上午1 11 19" src="https://user-images.githubusercontent.com/27427042/98972918-0ebee380-254e-11eb-9812-a33f02d259a5.png">

then goto directory re-run

```python
python setup.py clean
python setup.py build
python setup.py install
```

<img width="460" alt="截圖 2020-11-13 上午1 16 38" src="https://user-images.githubusercontent.com/27427042/98972986-226a4a00-254e-11eb-816f-bde2f051a55a.png">

**Comment by shihchun** [comment]
plot_coverage.py

![Snipaste_2020-11-16_13-07-43](https://user-images.githubusercontent.com/27427042/99217727-c0426b00-2813-11eb-884a-2373995ca8b7.png)

change to

```python
        self.config = ConfigParser.ConfigParser(allow_no_value=True,inline_comment_prefixes=(';',))
        self.config.read(pyu.getlong(_fileini,pstruc['DIRSIMUL']), encoding='utf-8')
```
![image](https://user-images.githubusercontent.com/27427042/99217937-2a5b1000-2814-11eb-935a-38e547c5cc42.png)


# KeyError: zfloor & zceil change to floor & ceil

![image](https://user-images.githubusercontent.com/27427042/99217672-97ba7100-2813-11eb-9ddd-e95607aa4ef6.png)

# cuz lots of script use zceil, so change TA-Office.lay

`pylayers\data\struc\lay\defstr.lay` have zceil

```
...
...

[indoor]
zceil = 3
```

so fix by change `pylayers\data\struc\lay\TA-Office.lay`,`ceil` to `zceil` `floor to zfloor`
```
...
...
[indoor]
floor = 0
ceil = 3
```

The command not update the `*.ini` file

```python
python setup.py clean
python setup.py build
python setup.py install
```

So I change the code in `pylayers\pylayers\gis\layouts.py`

```python
        if self.typ == 'indoor':
            if 'ceil' in di['indoor'].keys():
                self.zceil = eval(di['indoor']['ceil'])
                self.zfloor = eval(di['indoor']['floor'])
            else:
                self.zceil = eval(di['indoor']['zceil'])
                self.zfloor = eval(di['indoor']['zfloor'])
```
![image](https://user-images.githubusercontent.com/27427042/99217891-11525f00-2814-11eb-9dd3-1028e97435b7.png)


![image](https://user-images.githubusercontent.com/27427042/99224177-cb4fc800-2820-11eb-9a04-198134461e9d.png)

**Comment by shihchun** [comment]
```
python --version
Python 3.8.3
pip freeze > requirements.txt
conda list --explicit > spec-file.txt
conda env export > environment.yml
```
[requirements.txt](https://github.com/pylayers/pylayers/files/5544392/requirements.txt)
[spec-file.txt](https://github.com/pylayers/pylayers/files/5544393/spec-file.txt)
[environment.txt](https://github.com/pylayers/pylayers/files/5544953/environment.txt)

**Comment by cdd017** [comment]
hi ... Shishcun 
 i try to create conda env  as you describe in the  spec-file.
got this message :
Preparing transaction: done
Verifying transaction: failed

PaddingError: Placeholder of length '29' too short in package /home/dannyd/anaconda3/envs/pyl385/Library/bin/tcl86t.dll.
The package must be rebuilt with conda-build > 2.0. 

Can you Help Pleas ??
![image](https://user-images.githubusercontent.com/72920768/99224011-316f2780-27ee-11eb-948d-7a5d1a12fd3f.png)

**Comment by shihchun** [comment]
@cdd017 
I don't know about it, just export it = =
Maybe it's the prob, cuz I have the CUDA and GPU pytorch in it.
Sorry for that
I install on windows 10 Anaconda with the whl package, not on Linux wsl (=_=)

**Comment by shihchun** [comment]
![image](https://user-images.githubusercontent.com/27427042/99224469-54ff9580-2821-11eb-9631-499dc82b44fd.png)
You need to download them and install with

```sh
pip install /path_to_file/file_name
```

Then install with python

```sh
cd /path_to_pylayers.git
conda activate env_name
./installer_win.bat # install dependancy but some may need to install the lower version
python setup.py clean
python setup.py build
python setup.py install
pip list | findstr "pylayer"
pylayers                           0.5
```

**Comment by shihchun** [comment]
@cdd017 
![image](https://user-images.githubusercontent.com/27427042/99228335-6e0b4500-2827-11eb-8509-b13a86bef569.png)
I guess you can try this with yml file

**Comment by shihchun** [comment]
`\pylayers\pylayers\antprop\spharm.py`, when radiation plot (antenna pattern)

all `scipy.misc.factorial` change to `scipy.special.factorial`

```
# from scipy.misc
# to
from scipy.special import factorial
```

**Comment by cdd017** [comment]
Hi 
pleas can you create env YAML file  so i can clone the environment

**Comment by shihchun** [comment]
I already upload it. as environment.txt, check it out.

**Comment by shihchun** [comment]
@cdd017  

You can test this env on other issue I found, they test at 2018

[issue296](https://github.com/pylayers/pylayers/issues/296)

[environmentBase_cp36.yaml](https://github.com/shihchun/pylayers/blob/master/environmentBase_cp36.yaml)

**Comment by shihchun** [comment]
@cdd017 

I check the install on wsl Linux and my MacBook, I found the vtk install is complicated. I recommended you install with win10 + anaconda with the whl package. cuz the vtk need to build from source, just like the gccxml in ns3.  (= =)

I try the `environment.yaml`, the reason you can't create environment is cuz of the dependency version not support on your machine. you need add `#` to mark that line, after doing so,  it might not the env you want.

```sh
conda env create -f environmentBase_cp36.yaml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ruamel_yaml==0.15.46=py36h14c3975_0
  - jbig==2.1=hdba287a_0
  - scipy==1.1.0=py36hfa4b5c9_1
  - mpc==1.1.0=h10f8cd9_1
  - kiwisolver==1.0.1=py36hf484d3e_0
```


I provide my note to you. I build it successfully.

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/27427042/99569638-d6b31700-2a0b-11eb-81ed-8eae28eac13c.png">


# install note
open powershell with admin install chocolatey copy from their site

```sh
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```

install the display for wsl

```sh
choco install vcxsrv # install on windows open app bind the port 0 on admin cmd.exe
sudo apt-get install x11-apps # cmd type wsl to ubuntu
echo "export DISPLAY=127.0.0.1:0" >> ~/.bashrc  # wsl display bind port for x11 server
```

```sh
git clone pylayers
cd pylayers
./installer_unix
python setup.py clean
python setup.py build
python setup.py install
```

```sh
python ant.py
Layout:Mayavi is not installed # get error
```

I check the install package, the [vtk](https://pypi.org/project/vtk/#history) package on python pip, all the support after `vtk8.x`, and the libvtk version need to as same as the pip vtk version. (whl package is easy a lot !)

the apt-get test untial `libvtk6`, [build the vtk 8.2](https://discourse.vtk.org/t/installing-vtk-in-ubuntu-18-04/2147/4)

```sh
#sudo apt-get install libvtk6-dev #  you need to build from source 
# install the tool to build qt5...
sudo apt install cmake libavcodec-dev libavformat-dev libavutil-dev libboost-dev libdouble-conversion-dev libeigen3-dev libexpat1-dev libfontconfig-dev libfreetype6-dev libgdal-dev libglew-dev libhdf5-dev libjpeg-dev libjsoncpp-dev liblz4-dev liblzma-dev libnetcdf-dev libnetcdf-cxx-legacy-dev libogg-dev libpng-dev libpython3-dev libqt5opengl5-dev libqt5x11extras5-dev libsqlite3-dev libswscale-dev libtheora-dev libtiff-dev libxml2-dev libxt-dev qtbase5-dev qttools5-dev zlib1g-dev
cd ~
git clone https://github.com/Kitware/VTK.git
cd VTK
git checkout v8.2.0
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/vtk-inst \
    -DCMAKE_INSTALL_RPATH=$HOME/vtk-inst \
    -DVTK_Group_Qt=ON \
    -DVTK_QT_VERSION=5 \
    -DVTK_Group_Imaging=ON \
    -DVTK_Group_Views=ON \
    -DModule_vtkRenderingFreeTypeFontConfig=ON \
    -DVTK_WRAP_PYTHON=ON \
    -DVTK_PYTHON_VERSION=3 \
    -DPYTHON_EXECUTABLE=/usr/bin/python3 \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 \
    -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so \
    -DBUILD_TESTING=OFF \
    -DVTK_USE_SYSTEM_LIBRARIES=ON \
    -DVTK_USE_SYSTEM_LIBPROJ4=OFF \
    -DVTK_USE_SYSTEM_GL2PS=OFF \
    -DVTK_USE_SYSTEM_LIBHARU=OFF \
    -DVTK_USE_SYSTEM_PUGIXML=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    ..
make -j$(($(nproc) - 1)) # for a very long time
make install
```

```sh
pip install PyQt5 shapely # vtk # pip no vtk 8.2
# sudo apt-get install mayavi2
conda install -c cdat/label/v82 vtk-cdat # vtk 8.2
pip install mayavi
sudo apt-get install python3-pyproj
sudo apt-get install -y python-mpltoolkits.basemap
conda install basemap -c conda-forge # it install the pyproj geos

## see no module named...
pip install configobj simplejson
```

```sh
python ant.py
(base) ➜  test python ant.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-geek'
Traceback (most recent call last):
  File "ant.py", line 2, in <module>
    L=Layout('defstr.lay')
  File "/home/geek/anaconda3/lib/python3.7/site-packages/pylayers-0.5-py3.7.egg/pylayers/gis/layout.py", line 370, in __init__
  File "/home/geek/anaconda3/lib/python3.7/site-packages/pylayers-0.5-py3.7.egg/pylayers/gis/layout.py", line 2346, in load
  File "/home/geek/anaconda3/lib/python3.7/site-packages/pylayers-0.5-py3.7.egg/pylayers/gis/layout.py", line 2745, in add_segment
AttributeError: 'Graph' object has no attribute 'node'


Traceback (most recent call last):
  File "example/plot_coverage.py", line 16, in <module>
    C.show(figsize=(16,9),typ='pr',vmin=-120,vmax=-40)
  File "/home/geek/anaconda3/lib/python3.7/site-packages/pylayers-0.5-py3.7.egg/pylayers/antprop/coverage.py", line 986, in show
  File "/home/geek/anaconda3/lib/python3.7/site-packages/pylayers-0.5-py3.7.egg/pylayers/gis/layout.py", line 8754, in showG
  File "/home/geek/anaconda3/lib/python3.7/site-packages/pylayers-0.5-py3.7.egg/pylayers/util/graphutil.py", line 195, in draw
  File "/home/geek/anaconda3/lib/python3.7/site-packages/networkx/drawing/nx_pylab.py", line 518, in draw_networkx_edges
    if not cb.iterable(width):
AttributeError: module 'matplotlib.cbook' has no attribute 'iterable'
```

```sh
# Use some old version will fix it 
pip install networkx==2.0
pip install matplotlib==3.1.2
```

**Comment by cdd017** [comment]
Many thank for your efforts..
Ill try tomorrow morning to set it up ..
Thanks

בתאריך שבת, 21 בנוב׳ 2020, 16:10, מאת shihchun ‏<notifications@github.com>:
