### ISSUE TITLE
'Polygon' object has no attribute 'setvnodes_new'

### ISSUE THREAD

**Issue by isaac1369** [pylayers/pylayers#392]
Hi,

I installed pylayers and I want to run the 4 lines Ray-Tracing simulation. But, I get an error:
====================
 File "C:\Users\dehmollaian\pylayers\pylayers\gis\layout.py", line 6173, in <listcomp>
    [ polygon.setvnodes_new(self.get_points(polygon), self) for polygon in lTP ]
AttributeError: 'Polygon' object has no attribute 'setvnodes_new'
====================
Can you help me to fix it?

Best,
Isaac

**Comment by isaac1369** [comment]
Incorrect installation procedure!

**Comment by isaac1369** [comment]
I fixed the issue. The issue was that the installed version of Shapely was not the one mentioned in the requirements.txt

**Comment by summer2ice** [comment]
Hello, I also encountered the same problem. May I ask how you specifically solved it? version of Shapely? Thank you in advance

**Comment by summer2ice** [comment]
@isaac1369  Hello, I also encountered the same problem. May I ask how you specifically solved it? version of Shapely? Thank you in advance
