### ISSUE TITLE
Could use some help with installiation and running of the pylayers package

### ISSUE THREAD

**Issue by eriklindskog** [pylayers/pylayers#396]
I am trying to install and run a simulation with the pylayers Pyrhon package you have created but I am running into some problems.

I have downloaded and installed the requirte Python packages and downloaded to the pylayers code and run the setup in windows.

However, it is inclear to me how I proceed from here to run run a simulation using the package. Maybe someone would be able to provide some guidance?

**Comment by BrugerX** [comment]
Did you figure it out?
